name = "codex"
main = "app/controllers/index.js"
compatibility_date = "2025-12-17"
workers_dev = false
preview_urls = false
assets = { directory = "public" }

[[routes]]
pattern = "codex.wizards.art"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "codex"
database_id = "<YOUR DB>"

[[durable_objects.bindings]]
name = "SELLER_AGENT"
class_name = "SellerAgent"

[[migrations]]
tag = "v1"
new_classes = ["SellerAgent"]

[triggers]
crons = ["*/5 * * * *", "*/10 * * * *"]

[[rules]]
globs = ["**/*.html"]
type = "Text"
fallthrough = true

[[rules]]
globs = ["**/*.yml", "**/*.yaml"]
type = "Text"
fallthrough = true
